import argparse

parser = argparse.ArgumentParser(description='VadCLIP')
parser.add_argument('--seed', default=234, type=int)

parser.add_argument('--embed-dim', default=512, type=int)
parser.add_argument('--visual-length', default=256, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--visual-head', default=1, type=int)
parser.add_argument('--visual-layers', default=1, type=int)
parser.add_argument('--attn-window', default=32, type=int)
parser.add_argument('--prompt-prefix', default=10, type=int)
parser.add_argument('--prompt-postfix', default=10, type=int)
parser.add_argument('--classes-num', default=2, type=int)

parser.add_argument('--max-epoch', default=15, type=int)
parser.add_argument('--model-path', default='checkpoints/VadCLIP/')
parser.add_argument('--obj', type=str, default='hinge')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint_path', default='src/VadCLIP/checkpoints_trail/checkpoint.pth')
parser.add_argument('--batch-size', default=16, type=int)
parser.add_argument('--train-list', default='/home/lc/Desktop/wza/gy/dyna/bench/VadCLIP-main/list/train_list.csv')
parser.add_argument('--test-list', default='/home/lc/Desktop/wza/gy/dyna/bench/VadCLIP-main/list/test_list.csv')
# parser.add_argument('--gt-path', default='/home/lc/Desktop/wza/gy/dyna/bench/VadCLIP-main/list/gt.npy')
# parser.add_argument('--gt-segment-path', default='/home/lc/Desktop/wza/gy/dyna/bench/VadCLIP-main/list/gt_segment.npy')
# parser.add_argument('--gt-label-path', default='/home/lc/Desktop/wza/gy/dyna/bench/VadCLIP-main/list/gt_label.npy')

parser.add_argument('--lr', default=1e-5)
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[6,9,13])